### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by rclai** [meteor/postgres-packages#1]
```
root@profab-dev:~/pg-test/examples/react-todos/.knex# knex migrate:latest
Using environment: development

TypeError: object is not a function
    at initKnex (/root/.nvm/v0.10.36/lib/node_modules/knex/lib/bin/cli.js:68:10)
    at Command.<anonymous> (/root/.nvm/v0.10.36/lib/node_modules/knex/lib/bin/cli.js:103:15)
    at Command.listener (/root/.nvm/v0.10.36/lib/node_modules/knex/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/root/.nvm/v0.10.36/lib/node_modules/knex/node_modules/commander/index.js:610:12)
    at Command.parse (/root/.nvm/v0.10.36/lib/node_modules/knex/node_modules/commander/index.js:458:21)
    at Liftoff.invoke (/root/.nvm/v0.10.36/lib/node_modules/knex/lib/bin/cli.js:142:13)
    at Liftoff.<anonymous> (/root/.nvm/v0.10.36/lib/node_modules/knex/node_modules/liftoff/index.js:181:16)
    at module.exports (/root/.nvm/v0.10.36/lib/node_modules/knex/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/root/.nvm/v0.10.36/lib/node_modules/knex/node_modules/liftoff/index.js:174:9)
    at /root/.nvm/v0.10.36/lib/node_modules/knex/node_modules/liftoff/index.js:148:9
    at /root/.nvm/v0.10.36/lib/node_modules/knex/node_modules/v8flags/index.js:99:14
    at /root/.nvm/v0.10.36/lib/node_modules/knex/node_modules/v8flags/index.js:38:7
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
```

**Comment by Slava** [comment]
@stubailo do you have any idea what this report means?

Going to close this as this report doesn't hold to my standards of clarity and proper explanation.

**Comment by rclai** [comment]
I followed the instructions as written on the [`.knex` README](https://github.com/Slava/pg-example/tree/master/examples/react-todos/.knex):

```
npm install -g knex
npm install
knex migrate:latest
```

The first line you see on the OP paste is the last command above.

Does it have anything to do with the node.js version? I'm on 0.10.36.

**Comment by stubailo** [comment]
Works for me in node `0.10.29`, sounds like it could be a knex bug.

**Comment by rclai** [comment]
I deleted the .meteor/local and releases file, ran those three commands on .knex again and it works now.

**Comment by stubailo** [comment]
Cool, hehe. Not sure what happened there.
