### ISSUE TITLE
Cannot use 'in' operator to search for 'Plan'

### ISSUE THREAD

**Issue by aweis** [meteor/postgres-packages#11]
```
=> App running at: http://localhost:3000/
I20150825-00:15:50.348(-7)? Exception from sub publicLists id Hx9uTcJCBgLeXuMyN TypeError: Cannot use 'in' operator to search for 'Plan
s' in undefined
I20150825-00:15:50.349(-7)?     at checkNode (observe-driver/polling-driver.js:536:22)
I20150825-00:15:50.349(-7)?     at nodeWalker (observe-driver/polling-driver.js:541:10)
I20150825-00:15:50.350(-7)?     at findDependentRelations (observe-driver/polling-driver.js:547:10)
I20150825-00:15:50.350(-7)?     at PgLiveQuery._setupSelect (observe-driver/polling-driver.js:162:7)
I20150825-00:15:50.350(-7)?     at PgLiveQuery.select (observe-driver/polling-driver.js:59:12)
I20150825-00:15:50.350(-7)?     at [object Object].PG.Query.observe (pg.js:28:23)
I20150825-00:15:50.350(-7)?     at [object Object].PG.Query._publishCursor (pg.js:42:28)
I20150825-00:15:50.350(-7)?     at QueryBuilder.QBProto._publishCursor (collection-server.js:24:44)
I20150825-00:15:50.350(-7)?     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1042:1)
I20150825-00:15:50.350(-7)?     at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:825:1)
I20150825-00:15:50.350(-7)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:614:1)
I20150825-00:15:50.351(-7)?     at packages/ddp-server/livedata_server.js:548:1
```

postgres (PostgreSQL) 9.4.4, OSX Yosemite 10.10.5 (14F27)

I tried loading up the todos sample application, and I got the above error.  I followed the instructions here:  http://meteor-postgres.readthedocs.org/en/latest/

**Comment by stubailo** [comment]
Thanks for the report and trace! I'll look into it.

**Comment by Slava** [comment]
it will help if you actually give us the query causing this

**Comment by aweis** [comment]
Hi Slava and Sashko.  I believe the trace from above can be attributed to an issue with upgrading Postgres from 9.1 to 9.4.  I reinstalled Postgres following your documentation (http://meteor-postgres.readthedocs.org/en/latest/migrations/) and made a fresh db at /usr/local/var/postgres and now the react-todos works fine.  

I think it's safe to close this bug.

Thanks for your help.

**Comment by stubailo** [comment]
Ok, thanks for tracking it down!
