### ISSUE TITLE
package.js:44:7: Object [object Object] has no method 'addAssets'

### ISSUE THREAD

**Issue by iuraya** [meteor/postgres-packages#20]
Hi,

I'm following the tutorial for the react-todos and while launching the startup script i get this error:

Make sure you have created a DB called 'todos', and that you have run the migrations in .knex/
[[[[[ ~/Workspace/meteor/postgres-packages/examples/react-todos ]]]]]

=> Started proxy.  
TypeError: Object [object Object] has no method 'addAssets'
    at package.js:44:7
    at **bottom_mark** (/tools/utils/parse-stack.js:59:14)
    at [object Object]._.extend.initFromPackageDir (/tools/isobuild/package-source.js:1041:52)
    at /tools/packaging/catalog/catalog-local.js:286:23
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at initSourceFromDir (/tools/packaging/catalog/catalog-local.js:273:20)
    at /tools/packaging/catalog/catalog-local.js:345:9
    at /tools/utils/buildmessage.js:582:26
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/Kike/.meteor/packages/meteor-tool/.1.1.7-rc.3.91198t++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/utils/buildmessage.js:580:9
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at enterJob (/tools/utils/buildmessage.js:321:26)
    at Object.forkJoin (/tools/utils/buildmessage.js:542:3)
    at [object Object]._.extend._loadLocalPackages (/tools/packaging/catalog/catalog-local.js:341:18)
    at [object Object]._.extend.initialize (/tools/packaging/catalog/catalog-local.js:86:10)
    at /tools/project-context.js:573:29
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/project-context.js:565:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._.extend._initializeCatalog (/tools/project-context.js:564:13)
    at /tools/project-context.js:257:35
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
    at /tools/runners/run-app.js:523:29
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at bundleApp (/tools/runners/run-app.js:522:31)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:600:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:848:28)
    at /tools/runners/run-app.js:402:12
=> Errors prevented startup:                  

   While reading package from `/Users/Kike/Workspace/meteor/postgres-packages/packages/pg`:
   package.js:44:7: Object [object Object] has no method 'addAssets'

The database is well created, the migration has also gone well.

Thank you

**Comment by robfallows** [comment]
Try doing a `meteor update` - addAssets is new to V1.2

**Comment by iuraya** [comment]
Ok,

I've updated meteor to 1.2, but when updating the react todos to 1.2 i get the this:

/Users/Kike/Workspace/meteor/postgres-packages/examples/react-todos
MacBook-Pro-de-Enrique:react-todos Kike$ meteor update
Update to release METEOR@1.2.0.1 is impossible:
While selecting package versions:  
error: unknown package in top-level dependencies: simple:pg

This project is at the latest release which is compatible with your current package constraints.
=> Errors while upgrading packages:           

While selecting package versions:
error: unknown package in top-level dependencies: simple:pg

**Comment by rclai** [comment]
Just wait for #22 to get merged in.

**Comment by stubailo** [comment]
Fixed!
