### ISSUE TITLE
Query queue not found breaks write fence

### ISSUE THREAD

**Issue by rclai** [meteor/postgres-packages#29]
I'm not sure this is the right name to describe the issue, but pretty much this happens when I try to do a write. However, once I navigate somewhere else and go back to the page, the write will work properly.

Somehow, [this object](https://github.com/meteor/postgres-packages/blob/master/packages/pg/observe-driver/polling-driver.js#L85) is `undefined` at that moment.

```
Exception while invoking method 'todo_comments/insert' TypeError: Cannot call method 'some' of undefined
 at PgLiveQuery.appendPendingWrite (observe-driver/polling-driver.js:86:40)
 at QueryBuilder.run (collection-server.js:65:18)
 at [object Object].todo_commentsInsert (server/server.bundle.js:5213:1)
 at maybeAuditArgumentChecks (livedata_server.js:1692:12)
 at livedata_server.js:708:19
 at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
 at livedata_server.js:706:40
 at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
 at livedata_server.js:704:46
 at tryCallTwo (/root/.meteor/packages/promise/.0.4.8.1jq4den++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/domains/core.js:45:5)
 at doResolve (/root/.meteor/packages/promise/.0.4.8.1jq4den++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/domains/core.js:171:13)
 at new Promise (/root/.meteor/packages/promise/.0.4.8.1jq4den++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/domains/core.js:65:3)
 at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
 at livedata_server.js:548:43
I20150925-20:48:53.328(0)? Exception while invoking method 'todo_comments/insert' TypeError: Cannot call method 'some' of undefined
at PgLiveQuery.appendPendingWrite (observe-driver/polling-driver.js:92:40)
 at QueryBuilder.run (collection-server.js:65:18)
 at [object Object].todo_commentsInsert (server/server.bundle.js:5213:1)
 at maybeAuditArgumentChecks (livedata_server.js:1692:12)
 at livedata_server.js:708:19
 at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
 at livedata_server.js:706:40
 at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
 at livedata_server.js:704:46
 at tryCallTwo (/root/.meteor/packages/promise/.0.4.8.1jq4den++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/domains/core.js:45:5)
 at doResolve (/root/.meteor/packages/promise/.0.4.8.1jq4den++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/domains/core.js:171:13)
 at new Promise (/root/.meteor/packages/promise/.0.4.8.1jq4den++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/domains/core.js:65:3)
 at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
 at livedata_server.js:548:43
```

**Comment by stubailo** [comment]
@rclai protip: when you want to link to a specific line, hit `y` on your keyboard to get URL that goes to that specific commit. Right now, your link isn't pointing to anything and I'm not sure which object you were referring to.

**Comment by rclai** [comment]
Oh I didn't know that, thanks for the tip. It should be [this one](https://github.com/meteor/postgres-packages/blob/99b253cc11ba8c5ed13bb7cb6ba8ae6e71cb6660/packages/pg/observe-driver/polling-driver.js#L92).
