### ISSUE TITLE
Unable to run publish relation demo since merge of 99b253cc11

### ISSUE THREAD

**Issue by marcmunro** [meteor/postgres-packages#32]
The publish-relation demo crashes with the latest head.

This is is a freshly cloned copy of the repo.  The only local change I have made is to run_app.sh to set the postgres url, and then perform 

If I check out to the previous version (git checkout 14febbcd5fac1e2d902ac81df04f68ad86f50b6d) all is well.  If I check out to master I get the following:

```
=> Meteor 1.2.0.2 is available. Update this project with 'meteor update'.
W20150929-15:38:04.045(-7)? (STDERR)          
W20150929-15:38:04.047(-7)? (STDERR) /home/marc/.meteor/packages/meteor-tool/.1.1.7-rc.3.d9rf7m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150929-15:38:04.047(-7)? (STDERR)                        throw(ex);
W20150929-15:38:04.047(-7)? (STDERR)                              ^
W20150929-15:38:04.047(-7)? (STDERR) Error: Mongo accounts-password not plugged in yet
W20150929-15:38:04.047(-7)? (STDERR)     at new AccountsServer (packages/accounts-base/accounts_server.js:36:1)
W20150929-15:38:04.047(-7)? (STDERR)     at Package (packages/accounts-base/globals_server.js:5:1)
W20150929-15:38:04.047(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/packages/accounts-base.js:1798:4
W20150929-15:38:04.047(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/packages/accounts-base.js:1809:3
W20150929-15:38:04.048(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/boot.js:242:10
W20150929-15:38:04.048(-7)? (STDERR)     at Array.forEach (native)
W20150929-15:38:04.048(-7)? (STDERR)     at Function._.each._.forEach (/home/marc/.meteor/packages/meteor-tool/.1.1.7-rc.3.d9rf7m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150929-15:38:04.048(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
W20150929-15:38:07.773(-7)? (STDERR)          
W20150929-15:38:07.774(-7)? (STDERR) /home/marc/.meteor/packages/meteor-tool/.1.1.7-rc.3.d9rf7m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150929-15:38:07.774(-7)? (STDERR)                        throw(ex);
W20150929-15:38:07.774(-7)? (STDERR)                              ^
W20150929-15:38:07.788(-7)? (STDERR) Error: Mongo accounts-password not plugged in yet
W20150929-15:38:07.788(-7)? (STDERR)     at Package (packages/accounts-base/globals_server.js:5:1)
W20150929-15:38:07.788(-7)? (STDERR)     at new AccountsServer (packages/accounts-base/accounts_server.js:36:1)
W20150929-15:38:07.788(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/packages/accounts-base.js:1798:4
W20150929-15:38:07.788(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/packages/accounts-base.js:1809:3
W20150929-15:38:07.788(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/boot.js:242:10
W20150929-15:38:07.789(-7)? (STDERR)     at Array.forEach (native)
W20150929-15:38:07.789(-7)? (STDERR)     at Function._.each._.forEach (/home/marc/.meteor/packages/meteor-tool/.1.1.7-rc.3.d9rf7m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150929-15:38:07.789(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
W20150929-15:38:11.452(-7)? (STDERR)          
W20150929-15:38:11.453(-7)? (STDERR) /home/marc/.meteor/packages/meteor-tool/.1.1.7-rc.3.d9rf7m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150929-15:38:11.453(-7)? (STDERR)                        throw(ex);
W20150929-15:38:11.453(-7)? (STDERR)                              ^
W20150929-15:38:11.467(-7)? (STDERR) Error: Mongo accounts-password not plugged in yet
W20150929-15:38:11.467(-7)? (STDERR)     at new AccountsServer (packages/accounts-base/accounts_server.js:36:1)
W20150929-15:38:11.467(-7)? (STDERR)     at Package (packages/accounts-base/globals_server.js:5:1)
W20150929-15:38:11.467(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/packages/accounts-base.js:1798:4
W20150929-15:38:11.467(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/packages/accounts-base.js:1809:3
W20150929-15:38:11.468(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/boot.js:242:10
W20150929-15:38:11.468(-7)? (STDERR)     at Array.forEach (native)
W20150929-15:38:11.468(-7)? (STDERR)     at Function._.each._.forEach (/home/marc/.meteor/packages/meteor-tool/.1.1.7-rc.3.d9rf7m++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150929-15:38:11.468(-7)? (STDERR)     at /home/marc/proj/simian/meteor/postgres-packages/examples/publish-relation/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by marcmunro** [comment]
Please sssume the second sentence above actually says: 'this is a freshly cloned copy of the repo. The only local change I have made is to run_app.sh to set the postgres url.'
