### ISSUE TITLE
Exception on update

### ISSUE THREAD

**Issue by marcmunro** [meteor/postgres-packages#49]
In a simple app, with a `Click-Me` button updating a `buttons` table, clicking the button sometimes causes an exception in PgLiveQuery.  This is not 100% reproducible.  Generally I find that adding or changing a delay on the server side will trigger the problem (ie start app, click, if no problem, modify delay, wait for reload, click, etc)

I have been unable to  debug this - it seems to be a Heisenberg.  I am hoping that someone with more meteor-intenals-fu can figure something out.

You can get me code from https://github.com/marcmunro/poc3  You wil need to set up a suitable postgres database.  Instructions are provided in the README file.

Here is the stack trace:

```
=> App running at: http://localhost:3000/
I20151013-14:14:49.266(-7)? poc3
I20151013-14:14:59.619(-7)? Exception while invoking method '/updateCount' TypeError: Cannot call method 'some' of undefined
I20151013-14:14:59.620(-7)?     at PgLiveQuery.appendPendingWrite (meteor://💻app/observe-driver/polling-driver.js:96:40)
I20151013-14:14:59.620(-7)?     at QueryBuilder.run (meteor://💻app/collection-server.js:65:18)
I20151013-14:14:59.620(-7)?     at [object Object].Meteor.methods./updateCount (meteor://💻app/poc3.js:76:67)
I20151013-14:14:59.620(-7)?     at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1692:12)
I20151013-14:14:59.620(-7)?     at meteor://💻app/livedata_server.js:708:19
I20151013-14:14:59.620(-7)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151013-14:14:59.620(-7)?     at meteor://💻app/livedata_server.js:706:40
I20151013-14:14:59.621(-7)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151013-14:14:59.621(-7)?     at meteor://💻app/livedata_server.js:704:46
I20151013-14:14:59.621(-7)?     at tryCallTwo (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151013-14:14:59.621(-7)?     at doResolve (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151013-14:14:59.621(-7)?     at new Promise (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20151013-14:14:59.621(-7)?     at [object Object]._.extend.protocol_handlers.method (meteor://💻app/livedata_server.js:678:23)
I20151013-14:14:59.622(-7)?     at meteor://💻app/livedata_server.js:548:43
I20151013-14:14:59.626(-7)? Exception while invoking method '/updateCount' TypeError: Cannot call method 'some' of undefined
I20151013-14:14:59.626(-7)?     at PgLiveQuery.appendPendingWrite (meteor://💻app/observe-driver/polling-driver.js:96:40)
I20151013-14:14:59.626(-7)?     at QueryBuilder.run (meteor://💻app/collection-server.js:65:18)
I20151013-14:14:59.626(-7)?     at [object Object].Meteor.methods./updateCount (meteor://💻app/poc3.js:76:67)
I20151013-14:14:59.626(-7)?     at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1692:12)
I20151013-14:14:59.626(-7)?     at meteor://💻app/livedata_server.js:708:19
I20151013-14:14:59.626(-7)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151013-14:14:59.627(-7)?     at meteor://💻app/livedata_server.js:706:40
I20151013-14:14:59.627(-7)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151013-14:14:59.627(-7)?     at meteor://💻app/livedata_server.js:704:46
I20151013-14:14:59.627(-7)?     at tryCallTwo (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151013-14:14:59.627(-7)?     at doResolve (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151013-14:14:59.627(-7)?     at new Promise (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20151013-14:14:59.627(-7)?     at [object Object]._.extend.protocol_handlers.method (meteor://💻app/livedata_server.js:678:23)
I20151013-14:14:59.628(-7)?     at meteor://💻app/livedata_server.js:548:43
I20151013-14:14:59.630(-7)? Exception while invoking method '/updateCount' TypeError: Cannot call method 'some' of undefined
I20151013-14:14:59.630(-7)?     at PgLiveQuery.appendPendingWrite (meteor://💻app/observe-driver/polling-driver.js:96:40)
I20151013-14:14:59.631(-7)?     at QueryBuilder.run (meteor://💻app/collection-server.js:65:18)
I20151013-14:14:59.631(-7)?     at [object Object].Meteor.methods./updateCount (meteor://💻app/poc3.js:76:67)
I20151013-14:14:59.631(-7)?     at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1692:12)
I20151013-14:14:59.631(-7)?     at meteor://💻app/livedata_server.js:708:19
I20151013-14:14:59.631(-7)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151013-14:14:59.631(-7)?     at meteor://💻app/livedata_server.js:706:40
I20151013-14:14:59.631(-7)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151013-14:14:59.632(-7)?     at meteor://💻app/livedata_server.js:704:46
I20151013-14:14:59.632(-7)?     at tryCallTwo (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151013-14:14:59.632(-7)?     at doResolve (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151013-14:14:59.632(-7)?     at new Promise (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20151013-14:14:59.632(-7)?     at [object Object]._.extend.protocol_handlers.method (meteor://💻app/livedata_server.js:678:23)
I20151013-14:14:59.632(-7)?     at meteor://💻app/livedata_server.js:548:43
I20151013-14:14:59.637(-7)? Exception while invoking method '/updateCount' TypeError: Cannot call method 'some' of undefined
I20151013-14:14:59.637(-7)?     at PgLiveQuery.appendPendingWrite (meteor://💻app/observe-driver/polling-driver.js:96:40)
I20151013-14:14:59.637(-7)?     at QueryBuilder.run (meteor://💻app/collection-server.js:65:18)
I20151013-14:14:59.637(-7)?     at [object Object].Meteor.methods./updateCount (meteor://💻app/poc3.js:76:67)
I20151013-14:14:59.637(-7)?     at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1692:12)
I20151013-14:14:59.637(-7)?     at meteor://💻app/livedata_server.js:708:19
I20151013-14:14:59.637(-7)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151013-14:14:59.638(-7)?     at meteor://💻app/livedata_server.js:706:40
I20151013-14:14:59.638(-7)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151013-14:14:59.638(-7)?     at meteor://💻app/livedata_server.js:704:46
I20151013-14:14:59.638(-7)?     at tryCallTwo (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151013-14:14:59.639(-7)?     at doResolve (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151013-14:14:59.639(-7)?     at new Promise (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20151013-14:14:59.639(-7)?     at [object Object]._.extend.protocol_handlers.method (meteor://💻app/livedata_server.js:678:23)
I20151013-14:14:59.639(-7)?     at meteor://💻app/livedata_server.js:548:43
I20151013-14:14:59.643(-7)? Exception while invoking method '/updateCount' TypeError: Cannot call method 'some' of undefined
I20151013-14:14:59.643(-7)?     at PgLiveQuery.appendPendingWrite (meteor://💻app/observe-driver/polling-driver.js:96:40)
I20151013-14:14:59.643(-7)?     at QueryBuilder.run (meteor://💻app/collection-server.js:65:18)
I20151013-14:14:59.643(-7)?     at [object Object].Meteor.methods./updateCount (meteor://💻app/poc3.js:76:67)
I20151013-14:14:59.643(-7)?     at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1692:12)
I20151013-14:14:59.643(-7)?     at meteor://💻app/livedata_server.js:708:19
I20151013-14:14:59.643(-7)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151013-14:14:59.644(-7)?     at meteor://💻app/livedata_server.js:706:40
I20151013-14:14:59.644(-7)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151013-14:14:59.644(-7)?     at meteor://💻app/livedata_server.js:704:46
I20151013-14:14:59.644(-7)?     at tryCallTwo (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151013-14:14:59.644(-7)?     at doResolve (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151013-14:14:59.644(-7)?     at new Promise (/home/marc/.meteor/packages/promise/.0.5.0.puoksp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20151013-14:14:59.645(-7)?     at [object Object]._.extend.protocol_handlers.method (meteor://💻app/livedata_server.js:678:23)
I20151013-14:14:59.645(-7)?     at meteor://💻app/livedata_server.js:548:43
I20151013-14:15:18.161(-7)? poc3              
```

=> Meteor server restarted

https://github.com/marcmunro/poc3

**Comment by rclai** [comment]
Duplicate of #29.
