### ISSUE TITLE
password authentication failed on server startup

### ISSUE THREAD

**Issue by pjakobsen** [meteor/postgres-packages#62]
Testing the demo app examples/react-todos/ according to documentation on cheap VPS without root access

I'm able to run `knex migrate:latest`, so it's authenticating against Postgres no problem

But when I try `./run-app.sh`   I get:

`W20160508-00:16:27.862(-4)? (STDERR) error: password authentication failed for user "jakobsen"
W20160508-00:16:27.862(-4)? (STDERR)     at Object.Future.wait (/home/jakobsen/.meteor/packages/meteor-tool/.1.1.7-rc.3.10qk6ph++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20160508-00:16:27.862(-4)? (STDERR)     at PgLiveQuery._runQueries (observe-driver/polling-driver.js:516:22)
W20160508-00:16:27.862(-4)? (STDERR)     at PgLiveQuery._setupTriggers (observe-driver/polling-driver.js:241:10)
W20160508-00:16:27.862(-4)? (STDERR)     at new PgLiveQuery (observe-driver/polling-driver.js:22:10)
W20160508-00:16:27.863(-4)? (STDERR)     at Knex.Client.initializeDriver.driver (pg.js:7:14)
W20160508-00:16:27.863(-4)? (STDERR)     at /home/jakobsen/public_html/node/postgres-packages/examples/react-todos/.meteor/local/build/programs/server/packages/simple_pg.js:788:4
W20160508-00:16:27.863(-4)? (STDERR)     at /home/jakobsen/public_html/node/postgres-packages/examples/react-todos/.meteor/local/build/programs/server/packages/simple_pg.js:1051:3
W20160508-00:16:27.864(-4)? (STDERR)     at /home/jakobsen/public_html/node/postgres-packages/examples/react-todos/.meteor/local/build/programs/server/boot.js:242:10
W20160508-00:16:27.864(-4)? (STDERR)     at Array.forEach (native)
W20160508-00:16:27.864(-4)? (STDERR)     at Function._.each._.forEach (/home/jakobsen/.meteor/packages/meteor-tool/.1.1.7-rc.3.10qk6ph++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160508-00:16:27.864(-4)? (STDERR)     at /home/jakobsen/public_html/node/postgres-packages/examples/react-todos/.meteor/local/build/programs/server/boot.js:137:5
W20160508-00:16:27.864(-4)? (STDERR)     - - - - -
W20160508-00:16:27.864(-4)? (STDERR)     at [object Object].Connection.parseE (/home/jakobsen/public_html/node/postgres-packages/examples/react-todos/.meteor/local/isopacks/simple_pg/npm/node_modules/pg/lib/connection.js:539:11)
W20160508-00:16:27.864(-4)? (STDERR)     at [object Object].Connection.parseMessage (/home/jakobsen/public_html/node/postgres-packages/examples/react-todos/.meteor/local/isopacks/simple_pg/npm/node_modules/pg/lib/connection.js:366:17)
W20160508-00:16:27.865(-4)? (STDERR)     at Socket.<anonymous> (/home/jakobsen/public_html/node/postgres-packages/examples/react-todos/.meteor/local/isopacks/simple_pg/npm/node_modules/pg/lib/connection.js:105:22)
W20160508-00:16:27.865(-4)? (STDERR)     at Socket.emit (events.js:95:17)
W20160508-00:16:27.865(-4)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20160508-00:16:27.865(-4)? (STDERR)     at Socket.emit (events.js:92:17)
W20160508-00:16:27.865(-4)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20160508-00:16:27.865(-4)? (STDERR)     at emitReadable (_stream_readable.js:423:5)
W20160508-00:16:27.865(-4)? (STDERR)     at readableAddChunk (_stream_readable.js:166:9)
W20160508-00:16:27.865(-4)? (STDERR)     at Socket.Readable.push (_stream_readable.js:128:10)
W20160508-00:16:27.866(-4)? (STDERR)     at TCP.onread (net.js:529:21)`

**Comment by ziedmahdi** [comment]
@hexatonics did manage to find a solution?
I am facing the same problem on Cloud9

**Comment by ihafeez** [comment]
Update postgres URL with username and password will do magic for you.  

postgres://OSUser:OSpassword@127.0.0.1/dbname?USER=myuser&password=mypassword

The reason of this error is system trying to access through your os-user which requires password.
